# Generated by Django 3.1 on 2020-09-14 09:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='csv',
            field=models.FileField(storage=accounts.models.OverwriteStorage(), upload_to='file/csv/'),
        ),
    ]
