# Generated by Django 3.1 on 2020-09-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200914_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('csv', models.FileField(upload_to='file')),
            ],
        ),
    ]
